export default [
  {
    "id":0,
    "thumbnail":"../img/feed_main_news.jpg"
  },
  {
    "id":1,
    "thumbnail":"../img/banner_news_0.jpg",
    "category":"NEW PRODUCT",
    "delivery":"무료배송",
    "sale":"30%",
    "release":"단독발매",
    "title":"따사로운 가을의 사랑스러운 프렌치 룩",
    "desc":"따뜻한 오후 도심에서 여유롭게 가을을 즐기는 이미지를 풀어낸 보카바카의 이번 컬렉션은 파리를 배경으로 하는 영화 아멜리에에서 영감을 받아 사랑스러운 프렌치 룩을 재해석하였습니다.",
    "date":"8. 17. Thu - 8. 23. Wed",
    "mainImg":"../img/news_main_1.jpg",
    "brand_en":"VOCAVACA",
    "brand_ko":"보카바카",
    "brand_desc":"보카바카는 'VOCATION-VACATION'이라는 뜻으로 일과 쉼의 밸런스를 갖고 자신의 삶을 균형감 있게 유지하는 여성을 위한 브랜드입니다. 우아한 디테일과 편안한 실루엣, 좋은 소재라는 세 가지 요소에 충실합니다.",
    "collection_brand":"VOCAVACA",
    "collection":"COLLECTION",
    "col_1":"../img/news_col_1_1.jpg",
    "col_2":"../img/news_col_1_2.jpg",
    "col_3":"../img/news_col_1_3.jpg",
    "col_4":"../img/news_col_1_4.jpg",
    "col_5":"../img/news_col_1_5.jpg",
    "col_6":"../img/news_col_1_6.jpg",
    "col_7":"../img/news_col_1_7.jpg",
    "col_8":"../img/news_col_1_8.jpg",
    "col_9":"../img/news_col_1_9.jpg",
    "col_10":"../img/news_col_1_10.jpg",
  },
  {
    "id":2,
    "thumbnail":"../img/banner_news_1.jpg",
    "category":"NEW PRODUCT",
    "delivery":"무료배송",
    "sale":"~55%",
    "release":"단독 할인",
    "title":"특별한 여름을 보내요",
    "desc":"여름의 에너제틱한 모습을 담은 에트몽의 클리어런스 기획전 소식을 알려요. 단독 ~55%의 할인으로 진행되니 서두르세요.",
    "date":"8. 15. Tue - 8. 21. Mon",
    "mainImg":"../img/news_main_2.jpg",
    "brand_en":"ETMON",
    "brand_ko":"에트몽",
    "brand_desc":"에트몽 (ETMON)은 '내가 보는 나'에 대한 판타지를 디자인하고, 여성미를 강조한 과감한 디테일을 디자이너만의 절제된 감성으로 풀어내는 브랜드이다.",
    "collection_brand":"ETMON",
    "collection":"COLLECTION",
    "col_1":"../img/news_col_2_1.jpg",
    "col_2":"../img/news_col_2_2.jpg",
    "col_3":"../img/news_col_2_3.jpg",
    "col_4":"../img/news_col_2_4.jpg",
  }
]